on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/spruil/healthy_human.git"
          source_branch: "main"
          destination_repo: ${{ secrets.glitch_git_URL }}
          destination_branch: "main"
